### ISSUE TITLE
Phase 4 Project Template needs to either be changed or explained!

### ISSUE THREAD

**Issue by jacobmjones17** [learn-co-curriculum/phase-4-project-review-guidelines#3]
### Canvas Link

https://learning.flatironschool.com/courses/4333/pages/flex-phase-4-project-review-guidelines?module_item_id=336276

### Concern

When you go to the Github repository for the Project 4 Template that Flatiron reccomends us to use. First off, we no longer need to use Heroku and Postgresql in order to pass our project. But when I forked and cloned the template, and changed the gem file to Sqlite3, I couldn't migrate my tables which it took me a while to figure out why. 

It needs to be explained that you need to remove postgres from the Gemfile.rb and add sqlite3. But you also have to go inside of the database.yml file and remove postgres as the adapter and change it to Sqlite3. Then once you run bundle install again, then you can migrate your tables.

I am sure that I am not the only student that has had an issue with it. The instructor, Ben, said that he was going to leave a note as well.

### Suggested Changes

It needs to be explained that you need to remove postgres from the Gemfile.rb and add sqlite3. But you also have to go inside of the database.yml file and remove postgres as the adapter and change it to Sqlite3. Then once you run bundle install again, then you can migrate your tables.

I am sure that I am not the only student that has had an issue with it. The instructor, Ben, said that he was going to leave a note as well.

**Comment by lizbur10** [comment]
Hi @jacobmjones17 ! Thank you for bringing this to our attention. We have been in the process of updating the material in Phase 4 to use Render as the deployment tool rather than Heroku, and unfortunately it looks like you got caught in the gap! Apologies for the inconvenience.

The project template has now been updated, and includes the information you suggested at the top of the README.

Thanks for contributing to the Flatiron School curriculum 💙
